services:
  mongo:
    image: mongo:7
    container_name: restaurant_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: restaurant_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/restaurant_management_db
      - NODE_ENV=development
    depends_on:
      - mongo
    command: npm start

  seed:
    build: .
    container_name: restaurant_seed
    restart: "no"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/restaurant_management_db
      - NODE_ENV=development
    depends_on:
      - mongo
    command: sh -c "sleep 10 && npm run seed"

volumes:
  mongo_data: